
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: sitemap_parser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d sitemap_parser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sitemap-parser:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - FLASK_ENV=dev
      - DATABASE_URL=postgresql://app:strongpassword@postgres/sitemap_parser
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "443:5000"
    volumes:
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    command: >
      sh -c "gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 120 src.app:app"

  celery-worker:
    image: sitemap-parser:latest
    depends_on:
      - redis
      - postgres
    environment:
      - FLASK_ENV=dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://app:strongpassword@postgres/sitemap_parser
      - REDIS_URL=redis://redis:6379/0
    command: celery -A src.tasks.crawler worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
